stytchauth/stytch-node

- types/index.d.ts
Updating `/v1/magic_links/send_by_email` to include `email_id` field in response
> Add email_id to SendMagicByEmailResponse

- lib/stytchClient.js
- package-lock.json
- package.json
- test/stytchClient.test.js
When calling `getPendingUsers` with no arguments, I got an error.   I've changed it so this works as a request with all-default parameters (the nulls).
This is the only request method that doesn't just forward the arguments directly as a top-level parameters, so I don't think there are other cases like this one.
The error message I saw:
```
stytch/lib/stytchClient.js:106
starting_after_id: request["starting_after_id"] || null,
^
TypeError: Cannot read property 'starting_after_id' of undefined
```
> fix: Allow getPendingUsers to be called without arguments

- package-lock.json
I forgot to run `npm install` to update the lockfile's version number in #27.  This should happen before publishing v2.0.1 to NPM according to our publishing instructions.
> Fix version number in package-lock.json

- dist/client.js
- lib/client.ts
- package-lock.json
- package.json
- test/client.test.ts
- test/sandbox.test.ts
- types/lib/client.d.ts
The simple method aliasing in #34 didn't actually work. Calling one of those methods results in a TypeError saying `this.endpoint` is not a function, which makes sense in retrospect, since `endpoint` isn't bound to the constructed object.
To actually get the claimed backward compatibility (and avoid further problems with `this`), I've turned the alias methods into real methods that forward their arguments to the namespaced ones.
There's a new integration test for one of the alias methods. All the others follow the same pattern, so we should be able to get away with just this one test.
Remember that `/dist` and `/types` are entirely generated code.
> fix: Correct backward-compatibile method aliases

- dist/errors.js
- dist/shared.js
- lib/errors.ts
- lib/shared.ts
- package-lock.json
- package.json
- test/shared.test.ts
- types/lib/errors.d.ts
When using a client with an invalid Stytch env (for example, local testing without the server running), the error messages from endpoint methods were difficult to work with (the dreaded "[object Object]"). To make these debuggable, we now unpack the axios error into useful parts as a dedicated `RequestError` type.
There are new unit tests covering both cases.
Example error messages:
* Old
```
Error: [object Object]
at /.../node_modules/stytch/dist/shared.js:16:13
at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
* New
```
RequestError: connect ECONNREFUSED 127.0.0.1:8080
at /.../node_modules/stytch/dist/shared.js:17:13
at processTicksAndRejections (internal/process/task_queues.js:95:5) {
request: {
url: ...,
method: ...,
data: ...,
headers: ...,
...
}
}
```
> fix: Unpack axios errors for better debugging

- dist/users.js
- lib/users.ts
- package-lock.json
- package.json
- test/otps.test.ts
- test/users.test.ts
- types/lib/users.d.ts
This fixes a bug from the refactor to namespaced endpoints (#34). The `users` endpoints weren't using the shared `request` error handling, which threw unstructured errors from calls like `client.users.get("does-not-exist")`.
This also includes some other related changes:
- Correct the type signature for `users.update`/`updateUser`.  As originally typed, this call would construct an invalid request body.
- Fix copy-paste errors in OTPs unit tests
There are now unit tests for the `users` endpoints to verify the request config.
After upgrading our example apps through the betas, playing in a REPL, and reaching near-100% test coverage, I think this is ready to be called a stable v3, so I've removed the beta tag!
> fix: Handle response errors for users endpoints

- CODE_OF_CONDUCT.md
- DEVELOPMENT.md
- README.md
Update the README to use example credentials and tokens so they return "good" errors instead of 401s.
While I was here, I aligned the repo docs with our new standard template.
> docs: Update README to include runnable examples

- README.md
- package-lock.json
- package.json
Copy-pasting the example code into a REPL in a SyntaxError because import statements aren't allowed in that context.  To make copy-pasting work in more places, switch the example to CommonJS style.
> docs: Switch README example from ES6 to CJS

- index.cjs
- package-lock.json
- package.json
This wrapper is required by the `exports.import` field in `package.json`, but it was omitted from the published package.  This prevented an ES6 module import from being able to find the package.
The `index.cjs` file was also omitted from the published package for the same reason, which implies we don't need it anyway.
Errors look like this:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '.../node_modules/stytch/module.mjs' imported from .../test.js
Did you mean to import stytch/dist/index.js?
```
> fix: Include ES6 module wrapper in published package

- lib/magic_links.ts
- lib/otps.ts
- lib/shared.ts
- lib/users.ts
- package-lock.json
- package.json
- test/magic_links.test.ts
- test/shared.test.ts
- test/users.test.ts
- types/lib/magic_links.d.ts
- types/lib/otps.d.ts
- types/lib/shared.d.ts
- types/lib/users.d.ts
There are at least two problems with using `bigint`:
1. It only became available in ES2020, and it's rare to use that as a TS -> JS target.
2. It doesn't have a default JSON serialization, even as late as Node 16.
This PR changes `bigint` types to `number` types globally.
Versioning considerations: requests that used these fields didn't work at all with these TS types, so this is a bugfix.
> fix: Use number instead of bigint for numeric types

- test/shared.test.ts
This test was removed without deep investigation during #51 because it was blocking the release.  My current hypothesis is that we were relying on internal axios error message strings, which broke in the upgrade from v0.21.1 to v0.21.3.
To make this test more reliable and more representative of a realistic error, force the BigInt serialization problem. As a bonus, if we can ever start relying on BigInts to serialize, this test will fail, which will prompt us to consider using them again.
> dev: Bring back unsendable-request test

- test/sandbox.test.ts
Stytch API error messages now use periods at the end of sentences. This updates sandbox tests (which also function as examples) where they test for exact string matches on error messages.
> tests: Update sandbox error messages to match new formatting

- lib/shared.ts
- package-lock.json
- package.json
- types/lib/shared.d.ts
Expose the newly-added `last_authenticated_at` timestamp on sessions authentication factors.
I tested this by sending myself a magic link and verifying that `client.magicLinks.authenticate` (with `sessionDurationMinutes` set) returns the right timestamp on `res.session.authenticationFactors[0]`.
> feat: Add last_authenticated_at timestamp to authentication factors

- lib/shared.ts
- package-lock.json
- package.json
- types/lib/shared.d.ts
- Updates various OAuth factors to have correctly-named props
- Updates the `factor.last_authenticated_at` field to be a string (since we never parse it as a date)
- Adds `RecoveryCodeFactor` to the `AuthenticationFactor` sum type so callers can check it without needing to cast
> fix: Update Factor typedefs to match API response

- lib/shared.ts
- package-lock.json
- package.json
- types/lib/shared.d.ts
Ran `npm run build`. Also assuming we bump minor version for a change like this.
> Include authenticator_type in registration interface

- dist/sessions.js
- lib/sessions.ts
- package.json
- test/sessions.test.ts
Stytch session JWTs now include the session's `expires_at` value within the session data claim. If
present, prefer using that value to determine the session's expiration. For backward compatibility
with old tokens that don't include it, continue using the value from the "exp" claim.
> fix: Prefer session.expires_at value in session JWT claims

- dist/crypto_wallets.js
- dist/magic_links.js
- dist/oauth.js
- dist/otps.js
- dist/sessions.js
- dist/shared.js
- dist/totps.js
- dist/users.js
- dist/webauthn.js
- lib/__mocks__/shared.ts
- lib/crypto_wallets.ts
- lib/magic_links.ts
- lib/oauth.ts
- lib/otps.ts
- lib/sessions.ts
- lib/shared.ts
- lib/totps.ts
- lib/users.ts
- lib/webauthn.ts
- package-lock.json
- package.json
- types/lib/crypto_wallets.d.ts
- types/lib/magic_links.d.ts
- types/lib/oauth.d.ts
- types/lib/otps.d.ts
- types/lib/sessions.d.ts
- types/lib/shared.d.ts
- types/lib/totps.d.ts
- types/lib/users.d.ts
- types/lib/webauthn.d.ts
We now return a user object from the following calls:
- Create User
- Update User
- Authenticate Magic Link
- Authenticate OTP
- Authenticate OAuth
- Authenticate TOTP
- Authenticate WebAuthn
- Authenticate Crypto Wallet
- Delete Email / Phone # / TOTP / WebAuth / Crypto Wallet
>  feat: Add a user object to all authenticate and update calls

- lib/shared.ts
- package-lock.json
- package.json
- types/lib/shared.d.ts
The delivery factor was incorrectly set as `biometric_registration` when it should have been `biometric`.
> Update node delivery factor to "biometric"

- dist/sessions.js
- lib/sessions.ts
- package-lock.json
- package.json
- test/sandbox.test.ts
- test/sessions.test.ts
The return value of `authenticateJwtLocal` was missing the `custom_claims` object that `authenticate` populates. Because `authenticateJwt` prefers local validation over sending an API request, it would only include the custom claims when it had to fall back to the API request.
This change adds custom claim extraction to `authenticateJwtLocal` so all three methods agree again.
> fix: Extract custom claims from JWTs

- lib/sessions.ts
This was an error in #157. When I was developing the test for it, I had put the claims in the wrong place, so I needed this type definition to match.
But the session claim is a _sibling_ of the custom claims, not the parent, so this is incorrect.
No version update in this one because I caught this before completing the release. This will go out in v5.11.1 along with #157.
> fix: Remove incorrect type change to SessionClaim

- lib/totps.ts
- package-lock.json
- package.json
- types/lib/totps.d.ts
The TOTP create endpoint now returns a user ID and user field. This PR adds these fields to the TOTP CreateResponse in the node client library.
> Add user fields to TOTP create response

- test/sandbox.test.ts
The sandbox tests started failing in CI recently. The API was unable to sign the sandbox-session JWT for the CI project because the original signing key expired.
Normally, the key would automatically be rotated when it was necessary to sign the JWT for a real session. However, the CI project only ever issues sandbox requests and never starts a real session. So this uses the workaround of fetching the JWKS to trigger signing key generation outside the sandbox.
This is a _very_ specific edge case that would only be encountered by a very new or very old Stytch project whose first interaction with sessions is to try and validate the sandbox token. You should never have to use this anywhere in your real projects, Test or Live.
> ci: Ensure the CI project always has a JWT signing key

- lib/magic_links.ts
- lib/otps.ts
- package-lock.json
- package.json
- types/lib/magic_links.d.ts
- types/lib/otps.d.ts
We have optional user_id, session_token, and session_jwt arguments for magic links email send, OTP email/sms/whatsapp send now to attach the delivery method to a user.
> BACK-1935 OTP/magic link send attach method updates

- lib/crypto_wallets.ts
- package-lock.json
- package.json
- types/lib/crypto_wallets.d.ts
Attach to existing user via user_id already exists, add session params as well
> Cryptowallet attach via session params

- README.md
Removes "Beta" from in front of the Passwords product in the README.
> [DEV-594] Remove "Beta" from Passwords product in README

- lib/magic_links.ts
- lib/otps.ts
- lib/passwords.ts
- package-lock.json
- package.json
- test/magic_links.test.ts
- test/otps.test.ts
- test/password.test.ts
- types/lib/magic_links.d.ts
- types/lib/otps.d.ts
- types/lib/passwords.d.ts
Adds support for the `locale` parameter for the following endpoints:
- /magic_links/email/send
- /magic_links/email/login_or_create
- /magic_links/email/invite
- /otps/email/send
- /otps/email/login_or_create
- /otps/sms/send
- /otps/sms/login_or_create
- /otps/whatsapp/send
- /otps/whatsapp/login_or_create
- /passwords/email/reset/start
The `locale` parameter specifies the text language of the email that the user receives. Current `locale` options are "en" (English) and "es" (Spanish).
Support for the `locale` parameter has already been added to Stytch's API endpoints.
I've added the `locale` parameter to the integration tests for each endpoint.
> [SUP-8] Add locale parameter to Email Magic Links, OTP, and Passwords endpoints

- dist/oauth.js
- lib/oauth.ts
- package.json
- types/lib/oauth.d.ts
This adds support for an upcoming endpoint: OAuth Attach (`/v1/oauth/attach`).
> feat: Add support for OAuth Attach endpoint

- test/sandbox.test.ts
We recently started including the error code in the URL for direct links to error message descriptions. This updates the test expectations to match the new format.
No version bump needed because this won't be released on its own.
> dev: Update sandbox test error URL expectations

- lib/passwords.ts
- package-lock.json
- package.json
- test/password.test.ts
- types/lib/passwords.d.ts
This adds support for `phpass` hashes in the Password Migrate endpoint
> Add PHPass password hash type

- dist/client.js
- lib/base64.d.ts
- lib/client.ts
- package-lock.json
- package.json
Replaces https://github.com/ksheedlo/isomorphic-base64 with https://github.com/kevlened/b64-lite - the former has had a PR open to [fix Buffer deprecation warnings](https://github.com/ksheedlo/isomorphic-base64/pull/2) for several years and looks abandoned.
Fixes #171
> fix: Replace Isomorphic Base64 with b64-lite

- .github/workflows/test.yaml
Runs integration tests in all supported node versions, not just 16
> chore: Run integration tests in all supported node versions

- dist/base64.d.js
- dist/shared/base64.js
- dist/shared/client.js
- lib/base64.d.ts
- lib/shared/base64.ts
- lib/shared/client.ts
- package-lock.json
- package.json
- test/shared/base64.test.ts
- types/lib/shared/base64.d.ts
#185 is causing issues in NextJS edge middleware runtimes - see #191 
Let's stop depending on external base64 packages and just do it in vanilla JS.
> fix: Do not depend on an external base64 package anymore

- lib/b2c/passwords.ts
- package-lock.json
- package.json
- types/lib/b2c/passwords.d.ts
Adding the new password config options to `StrengthCheckResponse` to match [proto here](https://github.com/stytchauth/protobuf/blob/0d242bb6a7ae63f91a12fe8049a8e748977e2c0b/api/password/v1/password.proto#L172-L195)
I've never used node before, plz send help
> Add new LUDS options to StrengthCheckResponse

- lib/b2b/members.ts
- package-lock.json
- package.json
- test/b2b/members.test.ts
- types/lib/b2b/members.d.ts
Replaces the old singular `status` filter for member search with the plural `statuses`, which will take in an array of strings
> Add statuses plural filter for member search

- dist/b2b/client.js
- dist/b2c/client.js
- dist/shared/client.js
- lib/b2b/client.ts
- lib/b2c/client.ts
- lib/shared/client.ts
- package-lock.json
- package.json
- types/lib/b2b/client.d.ts
- types/lib/b2c/client.d.ts
- types/lib/shared/client.d.ts
Creates separate JWKS client URLs for B2B and B2C clients - B2B clients need `/b2b/sessions/jwks`, while B2C clients need `/sessions/jwks`
> fix: Use B2B JWKS endpoint for B2B projects

- lib/b2b/magic_links.ts
- package-lock.json
- package.json
- test/b2b/magic_links.test.ts
- types/lib/b2b/magic_links.d.ts
Adds the "locale" argument to the B2B EML endpoints.
> AUTH-716: Add support for non-English locales in B2B email magic links

- dist/b2b/sso.js
- lib/b2b/oidc.ts
- lib/b2b/sso.ts
- test/b2b/oidc.test.ts
- types/lib/b2b/sso.d.ts
> Add OIDC to SSO

- dist/shared/client.js
- lib/shared/client.ts
- package-lock.json
- package.json
- test/shared/client.test.ts
- types/lib/shared/client.d.ts
It's rare that someone would manually specify the environment unless they were working on something internally and wanted to hit internal development URLs. For every customer, they'd want the environment inferred from the given project ID (a test project can't be used in the live environment and vice versa).
This PR makes env an optional parameter and then sets it later depending on whether the project_id starts with `project-live-`.
> Infer environment from project_id

- .github/workflows/auto-publish.yml
Was not aware that registry-url is needed so the auth token would work properly.
https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
> Add registry-url during setup to allow for auto-publish

- lib/b2c/users.ts
- package-lock.json
- package.json
- types/lib/b2c/users.d.ts
The return type for the `deletePassword` method is `Promise<B2CUsersDeleteCryptoWalletResponse>`, but it looks like it should probably be `Promise<B2CUsersDeletePasswordResponse>`.
> Fix return type for deletePassword

- dist/index.js
- lib/index.ts
- types/lib/index.d.ts
Adds a default export so `import stytch from 'stytch'` doesn't resolve with `undefined`.
Closes #222
> chore: Add default export

- package-lock.json
- package.json
#255 accidentally left in the `9.0.0-rc.1` version. We're ready to release, so let's publish `9.0.0`
> fix: Publish non-rc version

- dist/b2b/rbac.js
- lib/b2b/discovery_organizations.ts
- lib/b2b/organizations.ts
- lib/b2b/organizations_members.ts
- lib/b2b/rbac.ts
- lib/b2c/passwords.ts
- package-lock.json
- package.json
- types/lib/b2b/discovery_organizations.d.ts
- types/lib/b2b/organizations.d.ts
- types/lib/b2b/organizations_members.d.ts
- types/lib/b2b/rbac.d.ts
- types/lib/b2c/passwords.d.ts
1. Docs updates
2. Adds support for `set_email_verified` in passwords/migrate
> Update docs and support set_email_verified

- dist/shared/errors.js
- lib/shared/errors.ts
- package-lock.json
- package.json
- types/lib/shared/errors.d.ts
Fixes #314
The issue is that the M2M token endpoint conforms to OAuth2-expected field names, which meant they didn't match our existing names from a StytchError -- since an end-user wouldn't particularly care about this difference when using the backend SDK, this PR simply converts the field names from the OAuth2 names to our StytchError names.
I created a simple script locally to create an M2M client and then try to get a token using a bogus client_secret.
Excerpt below:
> Convert OAuth2-style errors to StytchError equivalent

- DEVELOPMENT.md
- README.md
Update Slack Invite links to point to the Support landing page as a single source of truth (Slack invite links expire after 400 uses and need to be updated semi frequently).
> Update slack invite links

- dist/b2c/m2m.js
- lib/b2c/m2m.ts
- package.json
- types/lib/b2c/m2m.d.ts
We occasionally see JWT validation errors with the `nbf` claim that may be due to clock skew. This PR adds the `clock_tolerance_seconds` parameter to the M2M token authentication method (it already existed for the local authentication method) to allow for some clock drift.
> Add clock_tolerance_seconds to M2M token authentication

- package-lock.json
- package.json
Bumps `undici` and `jose` to latest. Not sure why Dependabot didn't do this for us?
> chore: Bump dependencies

- dist/shared/index.js
- lib/shared/index.ts
- package-lock.json
- package.json
- tsconfig.json
- types/lib/b2b/organizations.d.ts
- types/lib/b2b/organizations_members_oauth_providers.d.ts
- types/lib/b2c/m2m.d.ts
- types/lib/b2c/m2m_local.d.ts
- types/lib/b2c/users.d.ts
- types/lib/shared/index.d.ts
- types/lib/shared/sessions.d.ts
This PR:
- eliminates the use of `DOM` in `tsconfig.json` - previously we required all callers to either also have `DOM` or to disable library typechecking
- Updates `@types/node` and `typescript` to latest
- Starts to import the `BodyInit` type from `undici` 
No runtime code changes are made
> feat: [AUTH-4057] Clean up dependecy on DOM type usage

- dist/b2c/fraud_rules.js
- lib/b2c/fraud.ts
- lib/b2c/fraud_rules.ts
- package-lock.json
- package.json
- types/lib/b2c/fraud.d.ts
- types/lib/b2c/fraud_rules.d.ts
This PR adds support for IPGEO in the fraud rules endpoint. You can now set rules on CIDR blocks, ASNs, and country codes. The fingerprint lookup endpoint will now also return information on which rule type and identifier were applied, if a `RULE_MATCH` reason was returned.
> Add IPGEO to DFP rules endpoint

- module.mjs
- package-lock.json
- package.json
New build entrypoint has been published as `stytch@12.11.2-alpha.0` and validated in the following runtimes:
- Node (`import` and `require`)
- Deno
- Bun
- NextJS Edge
- Cloudflare Workers
- Cloudflare Workers + Vite
Closes #368
> fix: improve build compatibility

- dist/shared/errors.js
- lib/shared/errors.ts
- types/lib/shared/errors.d.ts
StytchErrors can have error_details on them, but those were not being passed through to the SDK. This change adds them to the error in the stytch-node SDK.
Testing:
You can test this for the `invalid_email_for_jit_provisioning` error that happens when trying to do a magic link or OTP loginOrSignup request when your email is not part of the allowed domains. This is the error after the changes, from a test app:
> Update stytch-node SDK to pass through error_details

- lib/b2b/organizations.ts
- package-lock.json
- package.json
- types/lib/b2b/organizations.d.ts
The Node SDK will accept arbitrary strings for the `filter_name` in the B2B organization search endpoint, so you don't technically have to upgrade to search by claimed domain. This PR adds the `claimed_email_domains` filter to the nice string type for the search operand as a minor update.
> Add claimed domains filter to B2B organization search

- dist/b2c/sessions.js
- lib/b2c/sessions.ts
- package.json
- types/lib/b2c/sessions.d.ts
This adds roles to the consumer session model type. This is a list of strings.
This is a major version increase due to adding a non-optional field.
> Add Roles to Consumer Session Model
