- lib/stytchRequest.js
- package-lock.json
- package.json
> Add User-Agent to Request

- lib/oauth.ts
- lib/sessions.ts
- lib/shared.ts
- package-lock.json
- package.json
- types/lib/oauth.d.ts
- types/lib/shared.d.ts
For product authenticate and sessions authenticate methods
> Adding support for authentication factors

- README.md
This PR documents which products our Node client library supports.
> Document supported products

- README.md
- dist/client.js
- dist/totps.js
- dist/users.js
- lib/client.ts
- lib/shared.ts
- lib/totps.ts
- lib/users.ts
- package-lock.json
- package.json
- test/totps.test.ts
- test/users.test.ts
- types/lib/client.d.ts
- types/lib/shared.d.ts
- types/lib/totps.d.ts
- types/lib/users.d.ts
Adds new totp endpoints & related updates to users
> Add TOTP Endpoints

- test-packages/commonjs/index.js
- test-packages/modules/index.js
Replaces /magic-links-urls with /redirect-urls.
> Replaces /magic-links-urls with /redirect-urls

- lib/oauth.ts
- package-lock.json
- package.json
- types/lib/oauth.d.ts
From https://github.com/stytchauth/stytch-node/pull/109, includes version bump
> Add stytch_session to oauth AuthenticateResponse

- dist/users.js
- lib/users.ts
- package-lock.json
- package.json
Closes #111, includes version bump
> Remove console.log from users.ts

- dist/index.js
- lib/index.ts
- types/lib/index.d.ts
want to be able to check that client errors are `instanceof StytchError` so I can give users more correct error info (i.e. session expiration will be a 401 explaining that where other Stytch errors might be a 500)
> export error classes

- package-lock.json
- package.json
> Bump version to 3.12.1

- lib/shared.ts
- package-lock.json
- package.json
- types/lib/shared.d.ts
> austin/gitlab: support gitlab as an oauth type

- .github/workflows/test.yaml
- README.md
- package.json
- test/sessions.test.ts
> feat: Define Node LTS support plan + test matrix

- lib/crypto_wallets.ts
- lib/magic_links.ts
- lib/oauth.ts
- lib/otps.ts
- lib/sessions.ts
- lib/shared.ts
- lib/totps.ts
- lib/webauthn.ts
- package-lock.json
- package.json
- types/lib/crypto_wallets.d.ts
- types/lib/magic_links.d.ts
- types/lib/oauth.d.ts
- types/lib/otps.d.ts
- types/lib/sessions.d.ts
- types/lib/shared.d.ts
- types/lib/totps.d.ts
- types/lib/webauthn.d.ts
- Add custom claims to authenticate requests & responses
- Custom claims will not be visible on the session object until the product is officially released
> feat: add custom claims support

- README.md
- dist/client.js
- dist/passwords.js
- lib/client.ts
- lib/magic_links.ts
- lib/oauth.ts
- lib/otps.ts
- lib/passwords.ts
- lib/shared.ts
- lib/users.ts
- package-lock.json
- package.json
- test/password.test.ts
- types/lib/client.d.ts
- types/lib/magic_links.d.ts
- types/lib/oauth.d.ts
- types/lib/otps.d.ts
- types/lib/passwords.d.ts
- types/lib/shared.d.ts
- types/lib/users.d.ts
The following PRs adds the various passwords methods to the client library. See https://stytch.com/docs/api/password-overview for more info
> Add Passwords to client library

- lib/shared.ts
- package-lock.json
- package.json
- types/lib/shared.d.ts
Sessions will soon have a biometric factor. This adds the typing for that factor.
> Add Biometric Factor to Sessions

- dist/users.js
- lib/users.ts
- package-lock.json
- package.json
- test/users.test.ts
- types/lib/users.d.ts
Delete user's biometric registration by the biometric_registration_id
> Add support to delete user's biometric registration

- lib/shared.ts
- package-lock.json
- package.json
- types/lib/shared.d.ts
> austin/oauth: figma, snapchat, tiktok, twitter

- lib/shared.ts
- package-lock.json
- package.json
- types/lib/shared.d.ts
Add Biometric Registrations to user object
> Add Biometric Registrations to user object

- lib/magic_links.ts
- lib/otps.ts
- lib/passwords.ts
- package.json
- types/lib/magic_links.d.ts
- types/lib/otps.d.ts
- types/lib/passwords.d.ts
Add template parameters to endpoints
> feat: Add template parameters

- .eslintrc.js
- .github/workflows/lint.yaml
- .github/workflows/test.yaml
- CODE_OF_CONDUCT.md
- DEVELOPMENT.md
- README.md
- babel.config.json
- jest.config.js
- package.json
- test/client.test.ts
- test/crypto_wallets.test.ts
- test/helpers.ts
- test/magic_links.test.ts
- test/oauth.test.ts
- test/otps.test.ts
- test/password.test.ts
- test/shared.test.ts
- test/totps.test.ts
- test/users.test.ts
- test/webauthn.test.ts
- tsconfig.json
Updates `package.json` to run prettier on all code, instead of just the stuff in `lib`
> feat: run prettier on entire repo

- dist/b2b/client.js
- dist/b2b/sessions.js
- dist/b2c/client.js
- dist/b2c/sessions.js
- dist/shared/client.js
- dist/shared/sessions.js
- lib/b2b/client.ts
- lib/b2b/sessions.ts
- lib/b2c/client.ts
- lib/b2c/sessions.ts
- lib/shared/client.ts
- lib/shared/sessions.ts
- test/b2b/sessions.test.ts
- types/lib/b2b/sessions.d.ts
- types/lib/b2c/sessions.d.ts
- types/lib/shared/client.d.ts
- types/lib/shared/sessions.d.ts
Adds the following methods to the B2B Sessions client:
- `jwks`
- `authenticateJwt`
- `authenticateJwtLocal`
> feat: Add support for Session JWT operations for B2B

- lib/b2c/users.ts
- test/b2c/users.test.ts
- types/lib/b2c/users.d.ts
> fix: Remove factors from user update request type

- lib/b2b/organizations.ts
- package-lock.json
- package.json
- types/lib/b2b/organizations.d.ts
`email_allowed_domains` is optional - make it so!
> fix: make org create email_allowed_domains optional

- .github/workflows/auto-publish.yml
- package-lock.json
- package.json
Detect whenever package.json changes -> when it does, publish the changes to NPM and also create a draft release on GitHub.
> Add auto-publish workflow

- package-lock.json
- package.json
> chore: release 8.1.0

- dist/b2c/magic_links_email.js
- dist/b2c/otps_email.js
- dist/b2c/otps_sms.js
- dist/b2c/otps_whatsapp.js
- dist/b2c/users.js
- lib/b2b/sessions.ts
- lib/b2c/magic_links_email.ts
- lib/b2c/otps_email.ts
- lib/b2c/otps_sms.ts
- lib/b2c/otps_whatsapp.ts
- lib/b2c/passwords_session.ts
- lib/b2c/sessions.ts
- lib/b2c/users.ts
- package-lock.json
- package.json
- types/lib/b2c/magic_links_email.d.ts
- types/lib/b2c/otps_email.d.ts
- types/lib/b2c/otps_sms.d.ts
- types/lib/b2c/otps_whatsapp.d.ts
- types/lib/b2c/passwords_session.d.ts
- types/lib/b2c/sessions.d.ts
- types/lib/b2c/users.d.ts
Adds additional params to the PasswordsSessionReset method and reruns autogen.
> feat: [AUTH-1645] Add additional params to PasswordsSessionReset

- dist/b2b/client.js
- lib/b2b/client.ts
- package-lock.json
- package.json
Fixes local JWT auth for B2B by using the correct JWKS URL
> Fix B2B local JWT auth logic

- dist/b2b/organizations_members.js
- lib/b2b/organizations_members.ts
- lib/b2b/passwords.ts
- package-lock.json
- package.json
- types/lib/b2b/organizations_members.d.ts
- types/lib/b2b/passwords.d.ts
`preserve_existing_sessions` should be an optional argument
> Mark preserve_existing_sessions optional

- package-lock.json
- package.json
Add MFA Method Org Settings and minor copy changes.
> Bump Package Version Minor (TOTP + copy)

- DEVELOPMENT.md
- README.md
Context: https://stytchio.slack.com/archives/C03VCND8D7Z/p1710859226666469
> Update Slack URLs

- lib/shared/errors.ts
- package-lock.json
- package.json
- types/lib/shared/errors.d.ts
Changes type from Map<string, string> to Map<string, any>
> Update error details type to account for nested map

- package-lock.json
> chore: Bump some vulnerable deps
